In [14]:
f = open("PycharmProjects/ML/EX1_LinearRegression/ex1data1.txt",'r')

In [27]:
import pandas as pd
data = pd.read_csv('PycharmProjects/ML/EX1_LinearRegression/ex1data1.csv')

In [28]:
print data.head()

   population   profit
0      6.1101  17.5920
1      5.5277   9.1302
2      8.5186  13.6620
3      7.0032  11.8540
4      5.8598   6.8233


In [29]:
print data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 2 columns):
population    97 non-null float64
profit        97 non-null float64
dtypes: float64(2)
memory usage: 1.6 KB
None


In [62]:
print data.describe()

       population     profit
count   97.000000  97.000000
mean     8.159800   5.839135
std      3.869884   5.510262
min      5.026900  -2.680700
25%      5.707700   1.986900
50%      6.589400   4.562300
75%      8.578100   7.046700
max     22.203000  24.147000


In [63]:
from matplotlib import pyplot as plt
data.plot(kind='scatter',  x='population', y ='profit', color='Blue', label='group1')
plt.title("Scatter plot of training data")
plt.xlabel("Profit in $10,000s")
plt.ylabel('Population of City in 10,000s')

In [66]:
plt.show()

In [70]:
Y = data[["profit"]].values

In [71]:
Y

array([[ 17.592  ],
       [  9.1302 ],
       [ 13.662  ],
       [ 11.854  ],
       [  6.8233 ],
       [ 11.886  ],
       [  4.3483 ],
       [ 12.     ],
       [  6.5987 ],
       [  3.8166 ],
       [  3.2522 ],
       [ 15.505  ],
       [  3.1551 ],
       [  7.2258 ],
       [  0.71618],
       [  3.5129 ],
       [  5.3048 ],
       [  0.56077],
       [  3.6518 ],
       [  5.3893 ],
       [  3.1386 ],
       [ 21.767  ],
       [  4.263  ],
       [  5.1875 ],
       [  3.0825 ],
       [ 22.638  ],
       [ 13.501  ],
       [  7.0467 ],
       [ 14.692  ],
       [ 24.147  ],
       [ -1.22   ],
       [  5.9966 ],
       [ 12.134  ],
       [  1.8495 ],
       [  6.5426 ],
       [  4.5623 ],
       [  4.1164 ],
       [  3.3928 ],
       [ 10.117  ],
       [  5.4974 ],
       [  0.55657],
       [  3.9115 ],
       [  5.3854 ],
       [  2.4406 ],
       [  6.7318 ],
       [  1.0463 ],
       [  5.1337 ],
       [  1.844  ],
       [  8.0043 ],
       [  1.0179 ],


In [69]:
import numpy as np

In [80]:
X_2 = data[["population"]].values

In [75]:
m = len(Y)
X_1 = np.ones((m,1))

In [77]:
X_1

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      

In [81]:
X_2

array([[  6.1101],
       [  5.5277],
       [  8.5186],
       [  7.0032],
       [  5.8598],
       [  8.3829],
       [  7.4764],
       [  8.5781],
       [  6.4862],
       [  5.0546],
       [  5.7107],
       [ 14.164 ],
       [  5.734 ],
       [  8.4084],
       [  5.6407],
       [  5.3794],
       [  6.3654],
       [  5.1301],
       [  6.4296],
       [  7.0708],
       [  6.1891],
       [ 20.27  ],
       [  5.4901],
       [  6.3261],
       [  5.5649],
       [ 18.945 ],
       [ 12.828 ],
       [ 10.957 ],
       [ 13.176 ],
       [ 22.203 ],
       [  5.2524],
       [  6.5894],
       [  9.2482],
       [  5.8918],
       [  8.2111],
       [  7.9334],
       [  8.0959],
       [  5.6063],
       [ 12.836 ],
       [  6.3534],
       [  5.4069],
       [  6.8825],
       [ 11.708 ],
       [  5.7737],
       [  7.8247],
       [  7.0931],
       [  5.0702],
       [  5.8014],
       [ 11.7   ],
       [  5.5416],
       [  7.5402],
       [  5.3077],
       [  7.

In [83]:
X = np.append(X_1,X_2)

In [85]:
X

array([  1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1.    ,
         1.    ,   1.    ,   1.    ,   1.    ,   1.    ,   1. 

In [88]:
np.hstack((X_1,X_2))

array([[  1.    ,   6.1101],
       [  1.    ,   5.5277],
       [  1.    ,   8.5186],
       [  1.    ,   7.0032],
       [  1.    ,   5.8598],
       [  1.    ,   8.3829],
       [  1.    ,   7.4764],
       [  1.    ,   8.5781],
       [  1.    ,   6.4862],
       [  1.    ,   5.0546],
       [  1.    ,   5.7107],
       [  1.    ,  14.164 ],
       [  1.    ,   5.734 ],
       [  1.    ,   8.4084],
       [  1.    ,   5.6407],
       [  1.    ,   5.3794],
       [  1.    ,   6.3654],
       [  1.    ,   5.1301],
       [  1.    ,   6.4296],
       [  1.    ,   7.0708],
       [  1.    ,   6.1891],
       [  1.    ,  20.27  ],
       [  1.    ,   5.4901],
       [  1.    ,   6.3261],
       [  1.    ,   5.5649],
       [  1.    ,  18.945 ],
       [  1.    ,  12.828 ],
       [  1.    ,  10.957 ],
       [  1.    ,  13.176 ],
       [  1.    ,  22.203 ],
       [  1.    ,   5.2524],
       [  1.    ,   6.5894],
       [  1.    ,   9.2482],
       [  1.    ,   5.8918],
       [  1.  

In [90]:
np.zeros((2,1))

array([[ 0.],
       [ 0.]])

In [127]:
h = X.dot(theta)
Z = h-Y
A = (((Z.T).dot(Z))[0][0])/(2*m)
A

32.072733877455669

In [129]:
theta

array([[ 0.],
       [ 0.]])

In [133]:
theta[0] = 1
theta

array([[ 1.],
       [ 0.]])

In [135]:
range(5)

[0, 1, 2, 3, 4]

In [139]:
np.ndarray([1,2]).dot(theta)

array([[ 0.]])

In [145]:
X.T.dot(Z)/m

array([[ -5.83913505],
       [-65.32884975]])

In [155]:
a = np.array([[1],[1]])
b =np.array([[1, 3.5]])

In [ ]:
b.dot(a)